steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-cloud-run', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-cloud-run']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - flask-cloud-run
      - --image
      - gcr.io/$PROJECT_ID/flask-cloud-run
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY

