steps:
# Step 1: Build the container image using Google Buildpacks
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - build
    - 'gcr.io/$PROJECT_ID/flask-cloud-run'
    - '--builder'
    - 'gcr.io/buildpacks/builder:v1'
    - '--path'
    - '.'

# Step 2: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - run
    - deploy
    - flask-cloud-run
    - --image
    - gcr.io/$PROJECT_ID/flask-cloud-run
    - --region
    - us-central1
    - --platform
    - managed
    - --allow-unauthenticated

# Use Cloud Logging to avoid GCS logs bucket requirements
options:
  logging: CLOUD_LOGGING_ONLY
